name: CI

on:
  push:
  pull_request:

jobs:
  PHPUnit:
    name: PHPUnit (PHP ${{ matrix.php }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-2022
        php:
          - 5.5
          - 5.4
          - 5.3
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
          ini-file: development
      - run: composer config secure-http false && composer config repo.packagist composer http://packagist.org && composer config preferred-install source
        if: ${{ matrix.os == 'windows-2022' && matrix.php < 5.5}}
      - run: composer install
        if: ${{ always() }}
      - run: vendor/bin/phpunit --coverage-text
        if: ${{ matrix.php >= 7.3 }}
      - run: vendor/bin/phpunit --coverage-text -c phpunit.xml.legacy
        if: ${{ matrix.php < 7.3 }}
